version: "3.9"
services:
    gateway:
        build: 
            context: ./
            dockerfile: ./cmd/gateway/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - gcommerce
        depends_on:
            - product-service
            - user-service
            - order-service
    product-service:
        build: 
            context: ./
            dockerfile: ./cmd/productServer/Dockerfile
        ports:
            - "8000:8000"
        networks:
            - gcommerce
    user-service:
        build: 
            context: ./
            dockerfile: ./cmd/userServer/Dockerfile
        ports:
            - "8001:8001"
        networks:
            - gcommerce
    order-service:
        build: 
            context: ./
            dockerfile: ./cmd/orderServer/Dockerfile
        ports:
            - "8002:8002"
        networks:
            - gcommerce
    testdb:
        image: mysql:5.7
        ports:
            - "3308:3306"
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: "ecommerce"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"

networks:
    gcommerce:
