version: "3.9"
services:
    gateway:
        build: ./cmd/gateway/Dockerfile
        ports:
            - "8080:8080"
    product-service:
        build: ./cmd/productServer/Dockerfile
        ports:
            - "8000:8000"
    user-service:
        build: ./cmd/userServer/Dockerfile
        ports:
            - "8001:8001"
    order-service:
        build: ./cmd/orderServer/Dockerfile
        ports:
            - "8002:8002"
