use ecommerce;

CREATE TABLE IF NOT EXISTS carts (
    id INTEGER PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_products (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    cart_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(128) NOT NULL,
    password VARCHAR(256) NOT NULL,
    credit INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    price INTEGER NOT NULL,
    stock INTEGER NOT NULL
);

